In [2]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


1. Create a Pandas Series of 5 numbers.

In [4]:
import pandas as pd
print(pd.Series([10,20,30,40,50]))

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
2. Create a Series with custom index.

In [6]:
import pandas as pd
print(pd.Series([10,20,30,40,50],index=["A","B","C","D","E"]))


A    10
B    20
C    30
D    40
E    50
dtype: int64


In [ ]:
3. Create a DataFrame with student names and marks.

In [15]:
import pandas as pd
a=pd.DataFrame({
    "Name":["Shreya","Satyam","Divya","Tiku"],
    "Marks":[90,95,85,86]
})
print(a)

     Name  Marks
0  Shreya     90
1  Satyam     95
2   Divya     85
3    Tiku     86


4.  Print: head(), shape, columns-

In [18]:
print(a.shape)
print(a.head())
print(a.columns)

(4, 2)
     Name  Marks
0  Shreya     90
1  Satyam     95
2   Divya     85
3    Tiku     86
Index(['Name', 'Marks'], dtype='str')


5. Select one column from DataFrame.

In [27]:
import pandas as pd
a=pd.DataFrame({
    "Name":["Shreya","Satyam","Divya","Tiku"],
    "Marks":[90,95,85,86]
})
print(a.Name)

0    Shreya
1    Satyam
2     Divya
3      Tiku
Name: Name, dtype: str


6. Select a row using loc

In [28]:
import pandas as pd
a=pd.DataFrame({
    "Name":["Shreya","Satyam","Divya","Tiku"],
    "Marks":[90,95,85,86]
})
print(a.loc[:])

     Name  Marks
0  Shreya     90
1  Satyam     95
2   Divya     85
3    Tiku     86


7.  Use loc to select the row with index 0 

In [29]:
import pandas as pd
a=pd.DataFrame({
    "Name":["Shreya","Satyam","Divya","Tiku"],
    "Marks":[90,95,85,86]
})
print(a.loc[0:])

     Name  Marks
0  Shreya     90
1  Satyam     95
2   Divya     85
3    Tiku     86


8. Use iloc to select the first row

In [30]:
import pandas as pd
a=pd.DataFrame({
    "Name":["Shreya","Satyam","Divya","Tiku"],
    "Marks":[90,95,85,86]
})
print(a.iloc[0])

Name     Shreya
Marks        90
Name: 0, dtype: object


9. Use loc to get only the Marks of index 2

In [ ]:
import pandas as pd
a=pd.DataFrame({
    "Name":["Shreya","Satyam","Divya","Tiku"],
    "Marks":[90,95,85,86]
})
print(a.loc[2, "Marks"])

85


10.  Use iloc to get marks using row and column position.

In [5]:
import pandas as pd
data = {
    "Name": ["Shreya", "Satyam", "Divya"],
    "Age": [21, 22, 23],
    "Marks": [80, 75, 90]
}
df = pd.DataFrame(data)
print(df)
print(df.iloc[1, 2])
print(df.iloc[0, 2])
print(df.iloc[2, 2])

     Name  Age  Marks
0  Shreya   21     80
1  Satyam   22     75
2   Divya   23     90
75
80
90


11. Select first two rows using both loc and iloc and observe the difference.

In [10]:
import pandas as pd
data = {
    "Name": ["Shreya", "Satyam", "Divya"],
    "Age": [21, 22, 23],
    "Marks": [80, 75, 90]
}
df = pd.DataFrame(data)
print(df.iloc[0:2])
print(df.loc[0:1])


     Name  Age  Marks
0  Shreya   21     80
1  Satyam   22     75
     Name  Age  Marks
0  Shreya   21     80
1  Satyam   22     75


12. Convert numpy array into DataFrame-

In [11]:
import numpy as np
import pandas as pd
# NumPy array 
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
# NumPy array convert into DataFrame 
df = pd.DataFrame(arr, columns=["A", "B", "C"], index=["Row1", "Row2", "Row3"])
print(arr) # numpy array
print(df)  # NumPy array convert into DataFrame 

[[10 20 30]
 [40 50 60]
 [70 80 90]]
       A   B   C
Row1  10  20  30
Row2  40  50  60
Row3  70  80  90
